apiVersion: v1
kind: Pod
metadata:
  name: web-frontend
  labels:
    app: web
spec:
  containers:
  - name: web-service-container
    image: us.icr.io/codey-cr/loyalty-web:latest
  imagePullSecrets:
  - name: roks43creds
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web-svc-label
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: web
